apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80        # Внешний порт, доступный снаружи
    targetPort: 3000  # Порт контейнера, на который нужно направить трафик
  type: LoadBalancer
