services: 
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres_dataflow
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT_DOCKER"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - databases_network

  mongo:
    image: mongo:6
    restart: always
    container_name: mongo_dataflow
    env_file:
      - .env
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_DB=$MONGO_DB
    ports:
      - "$MONGO_PORT:$MONGO_PORT_DOCKER"
    volumes:
      - mongo_data:/data/db
    networks:
      - databases_network

volumes:
  postgres_data:
  mongo_data:

networks:
  databases_network: